version: '3.9'

services:
  app:
    build:
      target: prod
    ports:
      - "80:8000"
    env_file:
      .env.prod
    deploy:
      restart_policy:
        condition: any

  db:
    deploy:
      restart_policy:
        condition: any
