"""remove year

Revision ID: 0150bacd547c
Revises: 4ae017cb000e
Create Date: 2023-07-26 18:41:18.560189

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0150bacd547c'
down_revision = '4ae017cb000e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
