"""add game status

Revision ID: 6a5718d68fed
Revises: e651c5b97956
Create Date: 2023-07-31 17:08:50.277741

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6a5718d68fed'
down_revision = 'e651c5b97956'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'status')
    # ### end Alembic commands ###
