"""game model orm_mode

Revision ID: e9be579130e6
Revises: 6a5718d68fed
Create Date: 2023-08-01 03:46:41.931586

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e9be579130e6'
down_revision = '6a5718d68fed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
