name: Server Health Check

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  workflow_run:
    workflows: [CD]
    types: [completed]


jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - id: server_check
        name: Check server status
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.API_ENDPOINT_URL }}/api/v1/health/)
          echo "RESPONSE=$RESPONSE" >> $GITHUB_OUTPUT
          
      - name: Determine Outcome
        run: |
          if [ "${{ steps.server_check.outputs.RESPONSE }}" = "200" ]; then
            exit 0  # Success
          else
            exit 1  # Failure
          fi