name: Restart

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      cleanup:
        description: Cleanup volumes attached to containers
        required: true
        type: boolean


permissions:
  contents: read

jobs:
  restart:
    name: Restart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create environment file
        run: |
          touch .env.prod
          echo "${{ secrets.ENV_VARS }}" >> .env.prod

      - name: Create and use docker context for production
        uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.SSH_HOST }}
          context_name: prod
          ssh_cert: ${{ secrets.SSH_KNOWN_HOSTS }}
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          use_context: true

      - name: Restart containers using Docker Compose
        if: ${{ !inputs.cleanup }}
        run: >
          docker-compose --project-directory .
          -f deploy/docker-compose.base.yml 
          -f deploy/docker-compose.prod.yml
          restart

      - name: Stop and remove containers using Docker Compose
        if: ${{ inputs.cleanup }}
        run: >
          docker-compose --project-directory .
          -f deploy/docker-compose.base.yml 
          -f deploy/docker-compose.prod.yml
          down -v

      - name: Start containers using Docker Compose
        if: ${{ inputs.cleanup }}
        run: >
          docker-compose --project-directory .
          -f deploy/docker-compose.base.yml
          -f deploy/docker-compose.prod.yml
          up -d

  health_check:
    needs: restart
    name: Post-Deployment Test
    uses: ./.github/workflows/health.yml
    secrets: inherit